### ISSUE TITLE
给网站添加favicon

### ISSUE THREAD

**Issue by SimpleCodeJust4Fun** [SimpleCodeJust4Fun/my-stack#1]

**Comment by SimpleCodeJust4Fun** [comment]
```
params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: /favicon.png
# e.g.: favicon placed in `static/favicon.ico` of your site folder, then set this field to `/favicon.ico` (`/` is necessary)
# 奇怪的错误是这里无法使用ico格式的图片，但是可以使用png
# 即：favicon: /favicon.png工作不正常，而favicon: /favicon.png工作正常
```
可以看到上面是stack主题官方的教程，但是mac m1上面出现了无法使用ico的情况，换成png就可以正常工作了
